### ISSUE TITLE
Issues with test run

### ISSUE THREAD

**Issue by SebastianEggert** [ferret-guy/adafruit_motor_hat#36]
* Adafruit-Motor-Hat version: Adafruit DC & Stepper Motor HAT for Raspberry Pi - mini Kit - 2348
* Python version: 2.7.13-2
* Operating System: Raspbian GNU/Linux 9

### **Description**

After installing your package via pip install, I performed the test run with the proposed command. I received a traceback which is shown below. 

Is the traceback due to false installation issues or HAT issues? Since am quite new in terms of Python programming and GitHub, it could be a beginner problem ;) 

Thanks a lot.

### **Terminal history**

pi@raspberrypi:~ $ pip install adafruit_motor_hat
Collecting adafruit_motor_hat
  Using cached adafruit_motor_hat-0.2.0-py2.py3-none-any.whl
Collecting Adafruit-GPIO>=0.7 (from adafruit_motor_hat)
Collecting adafruit-pureio (from Adafruit-GPIO>=0.7->adafruit_motor_hat)
  Using cached Adafruit_PureIO-0.2.1-py2-none-any.whl
Collecting spidev (from Adafruit-GPIO>=0.7->adafruit_motor_hat)
Installing collected packages: adafruit-pureio, spidev, Adafruit-GPIO, adafruit-motor-hat
Successfully installed Adafruit-GPIO-1.0.3 adafruit-motor-hat-0.2.0 adafruit-pureio-0.2.1 spidev-3.2
pi@raspberrypi:~ $ python -m unittest tests.test_adafruit_motor_hat
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib/python2.7/unittest/__main__.py", line 12, in <module>
    main(module=None)
  File "/usr/lib/python2.7/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/usr/lib/python2.7/unittest/main.py", line 149, in parseArgs
    self.createTests()
  File "/usr/lib/python2.7/unittest/main.py", line 158, in createTests
    self.module)
  File "/usr/lib/python2.7/unittest/loader.py", line 130, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib/python2.7/unittest/loader.py", line 100, in loadTestsFromName
    parent, obj = obj, getattr(obj, part)
AttributeError: 'module' object has no attribute 'test_adafruit_motor_hat'

**Comment by SebastianEggert** [comment]
Probably it was a reboot issue, as it seems to work now

### **History**

pi@raspberrypi:~ $ cd adafruit_motor_hat
pi@raspberrypi:~/adafruit_motor_hat $ python -m unittest tests.test_adafruit_motor_hat
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
pi@raspberrypi:~/adafruit_motor_hat $
